services:
  - type: web
    name: newsaggregator
    env: python
    pythonVersion: 3.12.7
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn newsaggregator.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: NEWS_API_KEY
        sync: false
      - key: ALLOWED_HOSTS
        value: ojt-internal.onrender.com

